[package]
name = "citygen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
glam = { version = "=0.32.1", default-features = false, features = ["std"] }
rand_chacha = { version = "=0.10.0", default-features = false }
serde = { workspace = true }

[dev-dependencies]
ron = { workspace = true }
